# Generated by Django 3.1.6 on 2021-02-14 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('date_time', models.DateTimeField(validators=[events.models.no_past])),
                ('latitute', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitute', models.DecimalField(decimal_places=6, max_digits=9)),
                ('attendes', models.ManyToManyField(related_name='events_attending', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
