# Generated by Django 3.1.6 on 2021-02-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='latitute',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
